---
- name: Install DNF plugins
  ansible.builtin.package:
    name: dnf-plugins-core
    state: latest

- name: Add Docker repository
  ansible.builtin.command: dnf config-manager --add-repo {{ docker_repo_url }}
  args:
    creates: /etc/yum.repos.d/docker-ce.repo

- name: Install Docker CE packages
  ansible.builtin.package:
    name:
    - docker-ce-{{ docker_version }}
    - docker-ce-cli-{{ docker_version }}
    - containerd.io-{{ containerd_version }}
    - docker-compose-plugin-{{ docker_compose_plugin_version }}
    state: present

- name: Enable and start Docker Engine service
  ansible.builtin.systemd:
    name: docker
    enabled: yes
    state: started
